version: '4.34.2' #docker version

services:
  www:
    build: 
      context: .
    volumes:
      - "./:/var/www/html"
    ports:
      - 80:80 
      - 443:443
  
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=restaurant-app
      - MYSQL_USER=restaurant-app
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports: 
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
